import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-additionalBlue flex items-center justify-center",
          inter.className
        )}
      >
        {children}
        {modal}
        <Image
          src="/trees.png"
          alt="trees"
          width={1920}
          height={1080}
          objectFit="cover"
          className="absolute w-full h-full -z-20 top-0 left-0 brightness-50 object-cover"
        />
        <Toaster />
        <footer className="fixed text-white flex justify-between items-center bottom-0 bg-deepBlue w-full px-4">
          <span>©Киберпротект</span>
          <span>2024</span>
        </footer>
      </body>
    </html>
  );
}
